import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import PageNav from "@/components/PageNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "overflow-x-hidden relative h-full antialiased"
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <div id="header">
            <PageNav />
          </div>
          <div
            className={cn(inter.className, "flex flex-grow flex-col flex-1")}
          >
            {children}
          </div>
          <div id="footer"></div>
        </main>
      </body>
    </html>
  );
}
